# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  displayName: 'Install nvm'

- script: source ~/.profile
  displayName: 'Reload profile'

- script: nvm install 10.15.3
  displayName: 'Use nvm'

- script: yarn install
  displayName: 'Install'

- script: yarn build 
  displayName: 'Build'
